Repository koosvary/Iconic, pull requests merged in 2018-08, with the labels that each got.

#1 Refactor ExpressionChromosome
  api/src/main/java/org/iconic/ea/chromosome/ExpressionChromosome.java
  api/src/main/java/org/iconic/ea/chromosome/LinearChromosome.java
  api/src/main/java/org/iconic/ea/chromosome/TreeChromosome.java
  api/src/main/java/org/iconic/ea/chromosome/expression/ExpressionChromosome.java
  api/src/main/java/org/iconic/ea/chromosome/graph/FunctionNode.java
  api/src/main/java/org/iconic/ea/chromosome/graph/InputNode.java
  api/src/main/java/org/iconic/ea/chromosome/graph/Node.java
  api/src/main/java/org/iconic/ea/gep/GeneExpressionProgramming.java
  api/src/main/java/org/iconic/ea/operator/evolutionary/crossover/gep/SimpleExpressionCrossover.java
  api/src/main/java/org/iconic/ea/operator/evolutionary/mutation/gep/ExpressionMutator.java
  api/src/main/java/org/iconic/ea/operator/objective/error/MeanSquaredError.java
  api/src/test/java/org/iconic/ea/chromosome/ExpressionChromosomeTest.java
  cli/src/main/java/org/iconic/Client.java
  client/src/main/java/org/iconic/project/search/SearchModel.java
Labels: api

#2 Add Chromosome Factories
  api/src/main/java/org/iconic/ea/EvolutionaryAlgorithm.java
  api/src/main/java/org/iconic/ea/chromosome/ChromosomeFactory.java
  api/src/main/java/org/iconic/ea/chromosome/expression/ExpressionChromosome.java
  api/src/main/java/org/iconic/ea/chromosome/expression/ExpressionChromosomeFactory.java
  api/src/main/java/org/iconic/ea/gep/GeneExpressionProgramming.java
  api/src/main/java/org/iconic/ea/operator/objective/DefaultObjective.java
  api/src/main/java/org/iconic/ea/operator/objective/ErrorBasedObjective.java
  api/src/main/java/org/iconic/ea/operator/objective/Objective.java
  api/src/main/java/org/iconic/ea/operator/primitive/FunctionalPrimitive.java
  api/src/test/java/org/iconic/ea/chromosome/expression/ExpressionChromosomeFactoryTest.java
  api/src/test/java/org/iconic/ea/chromosome/expression/ExpressionChromosomeTest.java
  cli/src/main/java/org/iconic/Client.java
  client/src/main/java/org/iconic/project/search/SearchModel.java
Labels: api, enhancement

#9 Add all primitive operator tests
  .gitignore
  api/src/test/java/org/iconic/ea/operator/primitive/AdditionTest.java
  api/src/test/java/org/iconic/ea/operator/primitive/ConstantTest.java
  api/src/test/java/org/iconic/ea/operator/primitive/CosTest.java
  api/src/test/java/org/iconic/ea/operator/primitive/DivisionTest.java
  api/src/test/java/org/iconic/ea/operator/primitive/MultiplicationTest.java
  api/src/test/java/org/iconic/ea/operator/primitive/PowerTest.java
  api/src/test/java/org/iconic/ea/operator/primitive/RootTest.java
  api/src/test/java/org/iconic/ea/operator/primitive/SinTest.java
  api/src/test/java/org/iconic/ea/operator/primitive/SubtractionTest.java
  api/src/test/java/org/iconic/ea/operator/primitive/TanTest.java
Labels: testing

#6 Redesign Data Input/Output Interface
  api/src/main/java/org/iconic/ea/EvolutionaryAlgorithm.java
  api/src/main/java/org/iconic/ea/chromosome/Chromosome.java
  api/src/main/java/org/iconic/ea/chromosome/ChromosomeFactory.java
  api/src/main/java/org/iconic/ea/chromosome/ExpressionChromosome.java
  api/src/main/java/org/iconic/ea/chromosome/LinearChromosome.java
  api/src/main/java/org/iconic/ea/chromosome/TreeChromosome.java
  api/src/main/java/org/iconic/ea/chromosome/expression/ExpressionChromosome.java
  api/src/main/java/org/iconic/ea/chromosome/expression/ExpressionChromosomeFactory.java
  api/src/main/java/org/iconic/ea/chromosome/graph/FunctionNode.java
  api/src/main/java/org/iconic/ea/chromosome/graph/InputNode.java
  api/src/main/java/org/iconic/ea/chromosome/graph/Node.java
  api/src/main/java/org/iconic/ea/data/DataManager.java
  api/src/main/java/org/iconic/ea/data/FeatureClass.java
  api/src/main/java/org/iconic/ea/data/NumericFeatureClass.java
  api/src/main/java/org/iconic/ea/data/preprocessing/Normalise.java
  api/src/main/java/org/iconic/ea/data/preprocessing/Offset.java
  api/src/main/java/org/iconic/ea/data/preprocessing/Preprocessor.java
  api/src/main/java/org/iconic/ea/gep/GeneExpressionProgramming.java
  api/src/main/java/org/iconic/ea/operator/evolutionary/crossover/gep/SimpleExpressionCrossover.java
  api/src/main/java/org/iconic/ea/operator/evolutionary/mutation/gep/ExpressionMutator.java
  api/src/main/java/org/iconic/ea/operator/objective/DefaultObjective.java
  api/src/main/java/org/iconic/ea/operator/objective/ErrorBasedObjective.java
  api/src/main/java/org/iconic/ea/operator/objective/Objective.java
  api/src/main/java/org/iconic/ea/operator/objective/error/MeanSquaredError.java
  api/src/main/java/org/iconic/ea/operator/primitive/FunctionalPrimitive.java
  api/src/test/java/org/iconic/ea/chromosome/ExpressionChromosomeTest.java
  api/src/test/java/org/iconic/ea/chromosome/expression/ExpressionChromosomeFactoryTest.java
  api/src/test/java/org/iconic/ea/chromosome/expression/ExpressionChromosomeTest.java
  api/src/test/java/org/iconic/ea/data/DataManagerTest.java
  api/src/test/resources/Iris-Header.txt
  api/src/test/resources/Iris-NoHeader.txt
  cli/src/main/java/org/iconic/Client.java
  client/src/main/java/org/iconic/project/dataset/DatasetModel.java
  client/src/main/java/org/iconic/project/search/SearchModel.java
  client/src/main/java/org/iconic/workspace/WorkspaceController.java
Labels: api, enhancement

#12 Feature/definition
  client/src/main/java/org/iconic/config/InMemoryModule.java
  client/src/main/java/org/iconic/project/DefineSearchController.java
  client/src/main/java/org/iconic/project/definition/DefineSearchController.java
  client/src/main/java/org/iconic/project/definition/DefineSearchService.java
  client/src/main/java/org/iconic/project/search/SearchModel.java
  client/src/main/java/org/iconic/workspace/WorkspaceController.java
  client/src/main/resources/views/workspace/DefineSearchView.fxml
Labels: enhancement, gui

#13 Fixed the issue with searching in the GUI
  client/src/main/java/org/iconic/project/search/SearchModel.java
Labels: gui

#14 Feature/gui
  api/src/main/java/org/iconic/ea/data/DataManager.java
  api/src/main/java/org/iconic/ea/data/FeatureClass.java
  api/src/main/java/org/iconic/ea/data/NumericFeatureClass.java
  api/src/main/java/org/iconic/ea/data/preprocessing/Normalise.java
  api/src/main/java/org/iconic/ea/data/preprocessing/Preprocessor.java
  api/src/main/java/org/iconic/ea/data/preprocessing/Smooth.java
  client/src/main/java/org/iconic/config/InMemoryModule.java
  client/src/main/java/org/iconic/project/DefineSearchController.java
  client/src/main/java/org/iconic/project/definition/DefineSearchController.java
  client/src/main/java/org/iconic/project/definition/DefineSearchService.java
  client/src/main/java/org/iconic/project/search/SearchModel.java
  client/src/main/java/org/iconic/workspace/WorkspaceController.java
  client/src/main/resources/views/workspace/DefineSearchView.fxml
  client/src/main/resources/views/workspace/ProcessDataView.fxml
Labels: enhancement, gui

#15 Quick patch to fix Preprocessor error
  api/src/main/java/org/iconic/ea/data/preprocessing/Preprocessor.java
  api/src/test/java/org/iconic/ea/operator/primitive/RootTest.java
Labels: bug

#21 Add Mockito example test
  api/build.gradle
  api/src/test/java/org/iconic/ea/operator/objective/DefaultObjectiveTest.java
Labels: testing

#22 Create method for a single-jar exectuable
  client/build.gradle
Labels: gui

#23 Feature/handlemissingvalues
  api/src/main/java/org/iconic/ea/data/preprocessing/HandleMissingValues.java
Labels: api, enhancement

#24 Feature/test updates
  api/build.gradle
  api/src/main/java/org/iconic/ea/data/preprocessing/HandleMissingValues.java
  api/src/main/java/org/iconic/ea/data/preprocessing/Offset.java
  api/src/main/java/org/iconic/ea/data/preprocessing/Preprocessor.java
  api/src/test/java/org/iconic/ea/data/preprocessing/HandleMissingValuesTest.java
  api/src/test/java/org/iconic/ea/data/preprocessing/OffsetTest.java
  api/src/test/java/org/iconic/ea/operator/objective/DefaultObjectiveTest.java
  api/src/test/java/org/iconic/ea/operator/objective/error/MeanSquaredErrorTest.java
Labels: api, testing

#5 Cartesian Genetic Programming
  api/build.gradle
  api/src/main/java/org/iconic/ea/EvolutionaryAlgorithm.java
  api/src/main/java/org/iconic/ea/chromosome/Chromosome.java
  api/src/main/java/org/iconic/ea/chromosome/ChromosomeFactory.java
  api/src/main/java/org/iconic/ea/chromosome/cartesian/CartesianChromosome.java
  api/src/main/java/org/iconic/ea/chromosome/cartesian/CartesianChromosomeFactory.java
  api/src/main/java/org/iconic/ea/chromosome/expression/ExpressionChromosome.java
  api/src/main/java/org/iconic/ea/chromosome/expression/ExpressionChromosomeFactory.java
  api/src/main/java/org/iconic/ea/operator/evolutionary/crossover/gep/SimpleExpressionCrossover.java
  api/src/main/java/org/iconic/ea/operator/evolutionary/mutation/Mutator.java
  api/src/main/java/org/iconic/ea/operator/evolutionary/mutation/cgp/CartesianSingleActiveMutator.java
  api/src/main/java/org/iconic/ea/operator/evolutionary/mutation/gep/ExpressionMutator.java
  api/src/main/java/org/iconic/ea/operator/objective/DefaultObjective.java
  api/src/main/java/org/iconic/ea/strategies/cgp/CartesianGeneticProgramming.java
  api/src/main/java/org/iconic/ea/strategies/gep/GeneExpressionProgramming.java
  api/src/test/java/org/iconic/ea/chromosome/cartesian/CartesianChromosomeFactoryTest.java
  api/src/test/java/org/iconic/ea/chromosome/cartesian/CartesianChromosomeTest.java
  api/src/test/java/org/iconic/ea/chromosome/expression/ExpressionChromosomeFactoryTest.java
  api/src/test/java/org/iconic/ea/operator/mutator/cgp/CartesianSingleActiveMutatorTest.java
  cli/src/main/java/org/iconic/Client.java
  cli/src/main/java/org/iconic/ea/EvolutionaryAlgorithmType.java
  cli/src/main/java/org/iconic/io/ArgsConverterFactory.java
  client/src/main/java/org/iconic/project/search/SearchModel.java
Labels: api, enhancement

#26 Patch/broken objective test
  api/src/test/java/org/iconic/ea/operator/objective/DefaultObjectiveTest.java
Labels: testing

#28 Release 0.3.0
  README.md
  api/build.gradle
  api/src/main/java/org/iconic/ea/EvolutionaryAlgorithm.java
  api/src/main/java/org/iconic/ea/chromosome/Chromosome.java
  api/src/main/java/org/iconic/ea/chromosome/ChromosomeFactory.java
  api/src/main/java/org/iconic/ea/chromosome/cartesian/CartesianChromosome.java
  api/src/main/java/org/iconic/ea/chromosome/cartesian/CartesianChromosomeFactory.java
  api/src/main/java/org/iconic/ea/chromosome/expression/ExpressionChromosome.java
  api/src/main/java/org/iconic/ea/chromosome/expression/ExpressionChromosomeFactory.java
  api/src/main/java/org/iconic/ea/data/preprocessing/HandleMissingValues.java
  api/src/main/java/org/iconic/ea/data/preprocessing/Offset.java
  api/src/main/java/org/iconic/ea/data/preprocessing/Preprocessor.java
  api/src/main/java/org/iconic/ea/operator/evolutionary/crossover/gep/SimpleExpressionCrossover.java
  api/src/main/java/org/iconic/ea/operator/evolutionary/mutation/Mutator.java
  api/src/main/java/org/iconic/ea/operator/evolutionary/mutation/cgp/CartesianSingleActiveMutator.java
  api/src/main/java/org/iconic/ea/operator/evolutionary/mutation/gep/ExpressionMutator.java
  api/src/main/java/org/iconic/ea/operator/objective/DefaultObjective.java
  api/src/main/java/org/iconic/ea/strategies/cgp/CartesianGeneticProgramming.java
  api/src/main/java/org/iconic/ea/strategies/gep/GeneExpressionProgramming.java
  api/src/test/java/org/iconic/ea/chromosome/cartesian/CartesianChromosomeFactoryTest.java
  api/src/test/java/org/iconic/ea/chromosome/cartesian/CartesianChromosomeTest.java
  api/src/test/java/org/iconic/ea/chromosome/expression/ExpressionChromosomeFactoryTest.java
  api/src/test/java/org/iconic/ea/data/preprocessing/HandleMissingValuesTest.java
  api/src/test/java/org/iconic/ea/data/preprocessing/OffsetTest.java
  api/src/test/java/org/iconic/ea/operator/mutator/cgp/CartesianSingleActiveMutatorTest.java
  api/src/test/java/org/iconic/ea/operator/objective/DefaultObjectiveTest.java
  api/src/test/java/org/iconic/ea/operator/objective/error/MeanSquaredErrorTest.java
  cli/build.gradle
  cli/src/main/java/org/iconic/Client.java
  cli/src/main/java/org/iconic/ea/EvolutionaryAlgorithmType.java
  cli/src/main/java/org/iconic/io/ArgsConverterFactory.java
  client/build.gradle
  client/src/main/java/org/iconic/project/search/SearchModel.java
Labels: api, cli, gui
