Repository koosvary/Iconic, pull requests merged in 2018-10, with the labels that each got.

#48 feature/inputFixes
  api/src/main/java/org/iconic/ea/data/DataManager.java
  client/src/main/java/org/iconic/project/InputDataController.java
Labels: api, enhancement, gui

#51 Feature/primitive descriptions
  api/src/main/java/org/iconic/ea/operator/primitive/AbsoluteValue.java
  api/src/main/java/org/iconic/ea/operator/primitive/Addition.java
  api/src/main/java/org/iconic/ea/operator/primitive/And.java
  api/src/main/java/org/iconic/ea/operator/primitive/ArcCos.java
  api/src/main/java/org/iconic/ea/operator/primitive/ArcSin.java
  api/src/main/java/org/iconic/ea/operator/primitive/ArcTan.java
  api/src/main/java/org/iconic/ea/operator/primitive/ArithmeticPrimitive.java
  api/src/main/java/org/iconic/ea/operator/primitive/Ceiling.java
  api/src/main/java/org/iconic/ea/operator/primitive/Constant.java
  api/src/main/java/org/iconic/ea/operator/primitive/Cos.java
  api/src/main/java/org/iconic/ea/operator/primitive/Division.java
  api/src/main/java/org/iconic/ea/operator/primitive/EqualTo.java
  api/src/main/java/org/iconic/ea/operator/primitive/Exponential.java
  api/src/main/java/org/iconic/ea/operator/primitive/Floor.java
  api/src/main/java/org/iconic/ea/operator/primitive/FunctionalPrimitive.java
  api/src/main/java/org/iconic/ea/operator/primitive/GaussianFunction.java
  api/src/main/java/org/iconic/ea/operator/primitive/GreaterThan.java
  api/src/main/java/org/iconic/ea/operator/primitive/GreaterThanOrEqual.java
  api/src/main/java/org/iconic/ea/operator/primitive/IfThenElse.java
  api/src/main/java/org/iconic/ea/operator/primitive/LessThan.java
  api/src/main/java/org/iconic/ea/operator/primitive/LessThanOrEqual.java
  api/src/main/java/org/iconic/ea/operator/primitive/LogisticFunction.java
  api/src/main/java/org/iconic/ea/operator/primitive/Maximum.java
  api/src/main/java/org/iconic/ea/operator/primitive/Minimum.java
  api/src/main/java/org/iconic/ea/operator/primitive/Modulo.java
  api/src/main/java/org/iconic/ea/operator/primitive/Multiplication.java
  api/src/main/java/org/iconic/ea/operator/primitive/NaturalLog.java
  api/src/main/java/org/iconic/ea/operator/primitive/Negation.java
  api/src/main/java/org/iconic/ea/operator/primitive/Not.java
  api/src/main/java/org/iconic/ea/operator/primitive/Or.java
  api/src/main/java/org/iconic/ea/operator/primitive/Power.java
  api/src/main/java/org/iconic/ea/operator/primitive/Root.java
  api/src/main/java/org/iconic/ea/operator/primitive/SignFunction.java
  api/src/main/java/org/iconic/ea/operator/primitive/Sin.java
  api/src/main/java/org/iconic/ea/operator/primitive/SquareRoot.java
  api/src/main/java/org/iconic/ea/operator/primitive/StepFunction.java
  api/src/main/java/org/iconic/ea/operator/primitive/Subtraction.java
  api/src/main/java/org/iconic/ea/operator/primitive/Tan.java
  api/src/main/java/org/iconic/ea/operator/primitive/Tanh.java
  api/src/main/java/org/iconic/ea/operator/primitive/TwoArcTan.java
  api/src/main/java/org/iconic/ea/operator/primitive/Xor.java
  api/src/main/resources/IrisNormalised.txt
  api/src/main/resources/dataChronicKidneyDisease.txt
  api/src/main/resources/dataChronicKidneyDisease2.txt
  api/src/test/java/org/iconic/ea/chromosome/cartesian/CartesianChromosomeTest.java
  client/src/main/java/org/iconic/project/BlockDisplay.java
  client/src/main/java/org/iconic/project/definition/DefineSearchController.java
  client/src/main/resources/views/workspace/DefineSearchView.fxml
Labels: api, enhancement, gui

#53 Updated changelog
  README.md
  api/build.gradle
  cli/build.gradle
  client/build.gradle
Labels: documentation

#55 Feature/smoothing window
  client/src/main/java/org/iconic/project/processing/ProcessDataController.java
  client/src/main/resources/views/workspace/ProcessDataView.fxml
Labels: enhancement, gui

#61 Patch/icon-service-collapsed-icons
  client/src/main/java/org/iconic/project/ProjectTreeController.java
Labels: gui

#60 Statistics panel updates as the search is progressing
  client/src/main/java/org/iconic/project/search/SearchExecutor.java
  client/src/main/java/org/iconic/project/search/SearchStatistics.java
  client/src/main/java/org/iconic/project/search/SolutionStorage.java
  client/src/main/java/org/iconic/project/search/StartSearchController.java
  client/src/main/resources/views/workspace/StartSearchView.fxml
Labels: enhancement, gui

#63 Ability to change UI themes
  client/src/main/java/org/iconic/Bootstrapper.java
  client/src/main/java/org/iconic/menu/MenuController.java
  client/src/main/java/org/iconic/project/search/SearchExecutor.java
  client/src/main/java/org/iconic/project/search/StartSearchController.java
  client/src/main/resources/css/bootstrap2.css
  client/src/main/resources/css/bootstrap3.css
  client/src/main/resources/css/dark-theme.css
  client/src/main/resources/css/light-theme.css
  client/src/main/resources/views/menu/MenuView.fxml
  client/src/main/resources/views/workspace/DefineSearchView.fxml
  client/src/main/resources/views/workspace/ProcessDataView.fxml
  client/src/main/resources/views/workspace/ReportView.fxml
  client/src/main/resources/views/workspace/ResultsView.fxml
  client/src/main/resources/views/workspace/StartSearchView.fxml
Labels: enhancement, gui

#64 Copy, Paste and Other Changes
  api/src/main/java/org/iconic/ea/data/DataManager.java
  client/src/main/java/org/iconic/project/definition/DefineSearchController.java
  client/src/main/java/org/iconic/project/input/InputDataController.java
  client/src/main/java/org/iconic/project/processing/ProcessDataController.java
  client/src/main/java/org/iconic/project/results/ResultsController.java
  client/src/main/java/org/iconic/project/search/StartSearchController.java
  client/src/main/resources/views/workspace/DefineSearchView.fxml
  client/src/main/resources/views/workspace/InputDataView.fxml
  client/src/main/resources/views/workspace/ProcessDataView.fxml
  client/src/main/resources/views/workspace/ResultsView.fxml
  client/src/main/resources/views/workspace/StartSearchView.fxml
Labels: enhancement, gui

#66 Cleanup/define search
  api/src/main/java/org/iconic/ea/operator/primitive/AbsoluteValue.java
  api/src/main/java/org/iconic/ea/operator/primitive/Addition.java
  api/src/main/java/org/iconic/ea/operator/primitive/And.java
  api/src/main/java/org/iconic/ea/operator/primitive/ArcCos.java
  api/src/main/java/org/iconic/ea/operator/primitive/ArcSin.java
  api/src/main/java/org/iconic/ea/operator/primitive/ArcTan.java
  api/src/main/java/org/iconic/ea/operator/primitive/Ceiling.java
  api/src/main/java/org/iconic/ea/operator/primitive/Constant.java
  api/src/main/java/org/iconic/ea/operator/primitive/Cos.java
  api/src/main/java/org/iconic/ea/operator/primitive/Division.java
  api/src/main/java/org/iconic/ea/operator/primitive/EqualTo.java
  api/src/main/java/org/iconic/ea/operator/primitive/Exponential.java
  api/src/main/java/org/iconic/ea/operator/primitive/Floor.java
  api/src/main/java/org/iconic/ea/operator/primitive/FunctionalPrimitive.java
  api/src/main/java/org/iconic/ea/operator/primitive/GaussianFunction.java
  api/src/main/java/org/iconic/ea/operator/primitive/GreaterThan.java
  api/src/main/java/org/iconic/ea/operator/primitive/GreaterThanOrEqual.java
  api/src/main/java/org/iconic/ea/operator/primitive/IfThenElse.java
  api/src/main/java/org/iconic/ea/operator/primitive/LessThan.java
  api/src/main/java/org/iconic/ea/operator/primitive/LessThanOrEqual.java
  api/src/main/java/org/iconic/ea/operator/primitive/LogisticFunction.java
  api/src/main/java/org/iconic/ea/operator/primitive/Maximum.java
  api/src/main/java/org/iconic/ea/operator/primitive/Minimum.java
  api/src/main/java/org/iconic/ea/operator/primitive/Modulo.java
  api/src/main/java/org/iconic/ea/operator/primitive/Multiplication.java
  api/src/main/java/org/iconic/ea/operator/primitive/NaturalLog.java
  api/src/main/java/org/iconic/ea/operator/primitive/Negation.java
  api/src/main/java/org/iconic/ea/operator/primitive/Not.java
  api/src/main/java/org/iconic/ea/operator/primitive/Or.java
  api/src/main/java/org/iconic/ea/operator/primitive/Power.java
  api/src/main/java/org/iconic/ea/operator/primitive/Root.java
  api/src/main/java/org/iconic/ea/operator/primitive/SignFunction.java
  api/src/main/java/org/iconic/ea/operator/primitive/Sin.java
  api/src/main/java/org/iconic/ea/operator/primitive/SquareRoot.java
  api/src/main/java/org/iconic/ea/operator/primitive/StepFunction.java
  api/src/main/java/org/iconic/ea/operator/primitive/Subtraction.java
  api/src/main/java/org/iconic/ea/operator/primitive/Tan.java
  api/src/main/java/org/iconic/ea/operator/primitive/Tanh.java
  api/src/main/java/org/iconic/ea/operator/primitive/TwoArcTan.java
  api/src/main/java/org/iconic/ea/operator/primitive/Xor.java
  client/src/main/java/org/iconic/project/search/SearchExecutor.java
  client/src/main/resources/views/workspace/DefineSearchView.fxml
Labels: gui

#68 Feature/expressions
  api/src/main/java/org/iconic/ea/chromosome/Chromosome.java
  api/src/main/java/org/iconic/ea/chromosome/graph/FunctionNode.java
  api/src/main/java/org/iconic/ea/chromosome/graph/InputNode.java
  api/src/test/java/org/iconic/ea/chromosome/cartesian/CartesianChromosomeTest.java
  cli/src/main/java/org/iconic/Client.java
  client/src/main/java/org/iconic/project/results/ResultsController.java
  client/src/main/java/org/iconic/project/search/SearchExecutor.java
Labels: api, cli, gui

#67 Implemented the handle missing values functionality for both the GUI …
  api/src/main/java/org/iconic/ea/data/DataManager.java
  api/src/main/java/org/iconic/ea/data/FeatureClass.java
  api/src/main/java/org/iconic/ea/data/preprocessing/HandleMissingValues.java
  api/src/main/java/org/iconic/ea/data/preprocessing/Normalise.java
  api/src/main/java/org/iconic/ea/data/preprocessing/Offset.java
  api/src/main/java/org/iconic/ea/data/preprocessing/RemoveOutliers.java
  api/src/main/java/org/iconic/ea/data/preprocessing/Smooth.java
  cli/src/main/java/org/iconic/Client.java
  client/src/main/java/org/iconic/project/processing/ProcessDataController.java
  client/src/main/resources/views/workspace/ProcessDataView.fxml
Labels: api, cli, gui

#69 Swapped normalise + remove outliers order for presentation
  client/src/main/resources/views/workspace/ProcessDataView.fxml
Labels: gui

#72 Feature/missingvaluesdialog
  client/src/main/java/org/iconic/project/definition/DefineSearchController.java
  client/src/main/java/org/iconic/project/search/StartSearchController.java
Labels: gui

#76 Feature/expressions
  api/src/main/java/org/iconic/ea/chromosome/Chromosome.java
  api/src/main/java/org/iconic/ea/chromosome/cartesian/CartesianChromosome.java
  api/src/main/java/org/iconic/ea/chromosome/graph/FunctionNode.java
  cli/src/main/java/org/iconic/Client.java
  client/src/main/java/org/iconic/project/results/ResultsController.java
Labels: api, cli, gui

#77 Feature/graph results expected actual second amendment
  api/src/main/java/org/iconic/ea/data/DataManager.java
  client/src/main/java/org/iconic/project/results/ResultsController.java
  client/src/main/resources/css/light-theme.css
  client/src/main/resources/views/workspace/ResultsView.fxml
  client/src/main/resources/views/workspace/StartSearchView.fxml
Labels: gui

#79 Cleanup/define search
  api/src/main/java/org/iconic/ea/operator/primitive/FunctionalPrimitive.java
  client/src/main/java/org/iconic/Bootstrapper.java
  client/src/main/java/org/iconic/project/definition/DefineSearchController.java
  client/src/main/java/org/iconic/project/search/config/CgpConfigurationModel.java
  client/src/main/java/org/iconic/project/search/config/GepConfigurationModel.java
  client/src/main/java/org/iconic/project/search/config/SearchConfigurationModel.java
  client/src/main/resources/views/project/ProjectTreeView.fxml
  client/src/main/resources/views/project/search/CgpConfigurationView.fxml
  client/src/main/resources/views/project/search/GepConfigurationView.fxml
  client/src/main/resources/views/workspace/DefineSearchView.fxml
Labels: bug, gui

#80 The selected chromosome is now found every time.
  client/src/main/java/org/iconic/project/results/ResultsController.java
  client/src/main/java/org/iconic/project/search/StartSearchController.java
  client/src/main/java/org/iconic/project/search/config/GepConfigurationModel.java
Labels: bug, gui

#81 Fix unused or broken elements for small screens
  client/src/main/resources/views/workspace/ResultsView.fxml
  client/src/main/resources/views/workspace/StartSearchView.fxml
Labels: bug, gui

#83 Add documentation to the client's search.config package
  client/src/main/java/org/iconic/project/input/InputDataController.java
  client/src/main/java/org/iconic/project/search/config/CgpConfigurationController.java
  client/src/main/java/org/iconic/project/search/config/CgpConfigurationModel.java
  client/src/main/java/org/iconic/project/search/config/GepConfigurationController.java
  client/src/main/java/org/iconic/project/search/config/GepConfigurationModel.java
  client/src/main/java/org/iconic/project/search/config/SearchConfigurationModel.java
Labels: documentation, gui

#85 Simply updated error function to 'Mean Squared Error'
  client/src/main/resources/views/workspace/DefineSearchView.fxml
  client/src/main/resources/views/workspace/StartSearchView.fxml
Labels: enhancement, gui

#78 Cleanup/standardize symbols
  api/src/main/java/org/iconic/ea/operator/primitive/GreaterThan.java
  api/src/main/java/org/iconic/ea/operator/primitive/GreaterThanOrEqual.java
  api/src/main/java/org/iconic/ea/operator/primitive/LessThan.java
  api/src/main/java/org/iconic/ea/operator/primitive/LessThanOrEqual.java
  api/src/main/java/org/iconic/ea/operator/primitive/Negation.java
Labels: api

#87 Search Pausing
  client/src/main/java/org/iconic/project/definition/DefineSearchController.java
  client/src/main/java/org/iconic/project/results/ResultsController.java
  client/src/main/java/org/iconic/project/search/SearchStatistics.java
  client/src/main/java/org/iconic/project/search/StartSearchController.java
  client/src/main/java/org/iconic/project/search/config/CgpConfigurationModel.java
  client/src/main/java/org/iconic/project/search/config/GepConfigurationModel.java
  client/src/main/java/org/iconic/project/search/config/SearchConfigurationModel.java
  client/src/main/java/org/iconic/project/search/io/SearchExecutor.java
  client/src/main/java/org/iconic/project/search/io/SearchState.java
Labels: bug, enhancement, gui

#89 Increased the speed of the graphing of results
  client/src/main/java/org/iconic/project/results/ResultsController.java
  client/src/main/java/org/iconic/project/search/io/SearchState.java
Labels: gui

#88 Constants thanks to Scott.
  api/src/main/java/org/iconic/ea/chromosome/expression/ExpressionChromosomeFactory.java
  api/src/main/java/org/iconic/ea/operator/evolutionary/mutation/gep/ExpressionMutator.java
Labels: api, enhancement

#92 Results update in real-time. Stop storing old results.
  client/src/main/java/org/iconic/project/results/ResultsController.java
  client/src/main/java/org/iconic/project/search/SolutionStorage.java
Labels: bug, gui

#97 Updated Readme for v 0.6.0
  README.md
  api/build.gradle
  cli/build.gradle
  client/build.gradle
Labels: documentation

#98 Ghetto fix for Chris' expression headers in solutions
  api/src/main/java/org/iconic/ea/chromosome/cartesian/CartesianChromosome.java
  api/src/main/java/org/iconic/ea/chromosome/cartesian/CartesianChromosomeFactory.java
  api/src/main/java/org/iconic/ea/chromosome/expression/ExpressionChromosome.java
  api/src/main/java/org/iconic/ea/chromosome/expression/ExpressionChromosomeFactory.java
  api/src/main/java/org/iconic/ea/chromosome/graph/InputNode.java
  api/src/main/java/org/iconic/ea/data/DataManager.java
  api/src/main/java/org/iconic/ea/operator/evolutionary/crossover/gep/SimpleExpressionCrossover.java
  api/src/main/java/org/iconic/ea/operator/evolutionary/mutation/gep/ExpressionMutator.java
  api/src/test/java/org/iconic/ea/chromosome/cartesian/CartesianChromosomeFactoryTest.java
  api/src/test/java/org/iconic/ea/chromosome/cartesian/CartesianChromosomeTest.java
  api/src/test/java/org/iconic/ea/chromosome/expression/ExpressionChromosomeFactoryTest.java
  api/src/test/java/org/iconic/ea/chromosome/expression/ExpressionChromosomeTest.java
  api/src/test/java/org/iconic/ea/operator/mutator/cgp/CartesianSingleActiveMutatorTest.java
  cli/src/main/java/org/iconic/Client.java
  client/src/main/java/org/iconic/project/results/ResultsController.java
  client/src/main/java/org/iconic/project/search/config/CgpConfigurationModel.java
  client/src/main/java/org/iconic/project/search/config/GepConfigurationModel.java
Labels: api, cli, gui
