Repository koosvary/Iconic, pull requests merged in 2018-09, with the labels that each got.

#29 Feature/preprocessing
  api/src/main/java/org/iconic/ea/data/DataManager.java
  api/src/main/java/org/iconic/ea/data/FeatureClass.java
  api/src/main/java/org/iconic/ea/data/preprocessing/HandleMissingValues.java
  api/src/main/java/org/iconic/ea/data/preprocessing/Offset.java
  api/src/main/java/org/iconic/ea/data/preprocessing/RemoveOutliers.java
  api/src/main/java/org/iconic/ea/data/preprocessing/TransformType.java
  api/src/main/java/org/iconic/ea/data/preprocessing/Transformation.java
  api/src/test/java/org/iconic/ea/data/preprocessing/OffsetTest.java
  client/src/main/java/org/iconic/workspace/WorkspaceController.java
  client/src/main/resources/views/workspace/ProcessDataView.fxml
Labels: enhancement, gui

#34 Feature/results page
  api/src/main/java/org/iconic/ea/chromosome/Chromosome.java
  api/src/main/java/org/iconic/ea/chromosome/cartesian/CartesianChromosome.java
  api/src/main/java/org/iconic/ea/chromosome/expression/ExpressionChromosome.java
  api/src/main/java/org/iconic/ea/chromosome/graph/Node.java
  client/src/main/java/org/iconic/project/results/ResultDisplay.java
  client/src/main/java/org/iconic/project/results/ResultsController.java
  client/src/main/java/org/iconic/project/search/SearchModel.java
  client/src/main/java/org/iconic/project/search/SolutionStorage.java
  client/src/main/resources/views/workspace/ResultsView.fxml
Labels: enhancement, gui

#35 Feature/inputtab
  api/src/main/java/org/iconic/ea/data/DataManager.java
  client/src/main/java/org/iconic/project/InputDataController.java
  client/src/main/resources/views/workspace/InputDataView.fxml
Labels: enhancement, gui

#37 Feature/preprocessing
  api/src/main/java/org/iconic/ea/data/DataManager.java
  api/src/main/java/org/iconic/ea/data/FeatureClass.java
  api/src/main/java/org/iconic/ea/data/preprocessing/HandleMissingValues.java
  api/src/main/java/org/iconic/ea/data/preprocessing/Normalise.java
  api/src/main/java/org/iconic/ea/data/preprocessing/Offset.java
  api/src/main/java/org/iconic/ea/data/preprocessing/Preprocessor.java
  api/src/main/java/org/iconic/ea/data/preprocessing/RemoveOutliers.java
  api/src/main/java/org/iconic/ea/data/preprocessing/Smooth.java
  api/src/main/java/org/iconic/ea/data/preprocessing/Transformation.java
  api/src/test/java/org/iconic/ea/data/preprocessing/OffsetTest.java
  client/src/main/java/org/iconic/project/processing/ProcessDataController.java
  client/src/main/resources/views/workspace/ProcessDataView.fxml
Labels: enhancement, gui

#39 Feature/definition backend
  api/src/main/java/org/iconic/ea/chromosome/expression/ExpressionChromosome.java
  api/src/main/java/org/iconic/ea/data/DataManager.java
  api/src/main/java/org/iconic/ea/data/FeatureClass.java
  client/src/main/java/org/iconic/project/definition/DefineSearchController.java
  client/src/main/java/org/iconic/project/search/SearchModel.java
Labels: api, enhancement

#43 Feature/infinite generations
  client/src/main/java/org/iconic/project/search/SearchModel.java
Labels: gui

#36 Feature/expressions
  api/src/main/java/org/iconic/ea/chromosome/Chromosome.java
  api/src/main/java/org/iconic/ea/chromosome/cartesian/CartesianChromosome.java
  api/src/test/java/org/iconic/ea/chromosome/cartesian/CartesianChromosomeTest.java
  cli/src/main/java/org/iconic/Client.java
Labels: api, cli, testing

#44 Feature/prerelease v0.4.0
  README.md
  api/build.gradle
  cli/build.gradle
  client/build.gradle
Labels: documentation

#42 Feature/create dataset
  api/src/main/java/org/iconic/ea/data/DataManager.java
  client/src/main/java/org/iconic/project/InputDataController.java
  client/src/main/java/org/iconic/project/dataset/DatasetModel.java
  client/src/main/resources/views/workspace/InputDataView.fxml
Labels: enhancement, gui
