Repository koosvary/Iconic, pull requests merged in 2018-11, with the labels that each got.

#100 Added negative numbers for constants, now ranges between -100 and 100
  api/src/main/java/org/iconic/ea/chromosome/expression/ExpressionChromosomeFactory.java
  api/src/main/java/org/iconic/ea/operator/evolutionary/mutation/gep/ExpressionMutator.java
Labels: gui

#104 Bug fixed to spreadsheet
  client/src/main/java/org/iconic/menu/MenuController.java
  client/src/main/java/org/iconic/project/input/InputDataController.java
  client/src/main/resources/views/menu/MenuView.fxml
Labels: bug, gui

#102 Fix incorrect values being plotted in the solution fit plot
  api/src/main/java/org/iconic/ea/chromosome/Chromosome.java
  client/src/main/java/org/iconic/project/results/ResultsController.java
  client/src/main/java/org/iconic/project/search/config/CgpConfigurationModel.java
Labels: gui

#103 Change graph export format from PDF to PNG and remove axis scaling
  api/src/main/java/org/iconic/ea/strategies/gsemo/GSEMO.java
  cli/src/main/java/org/iconic/Client.java
  cli/src/main/java/org/iconic/utils/GraphWriter.java
  cli/src/main/java/org/iconic/utils/XYGraphWriter.java
Labels: cli

#108 Let users specify what primitives to use from the CLI and fixes a bug
  README.md
  build.gradle
  cli/src/main/java/org/iconic/Client.java
  cli/src/main/java/org/iconic/io/cli/ArgsConverterFactory.java
  cli/src/main/java/org/iconic/io/cli/PrimitiveTypeConverter.java
  cli/src/main/java/org/iconic/io/cli/PrimitiveTypeConverterFactory.java
Labels: cli, enhancement

#110 Readme 2.0
  README.md
  docs/images/HeaderLength.png
  docs/images/HighLevelArchitectureDiagram.png
  docs/images/TargetExpressionSyntax.png
  docs/images/cli/example-run-basic.png
  docs/images/cli/results-all.png
  docs/images/cli/results-final.png
  docs/images/cli/solution-fit.png
  docs/images/gettingStarted/AddSearchDialog.png
  docs/images/gettingStarted/DefineSearchCgp.png
  docs/images/gettingStarted/DefineSearchGep.png
  docs/images/gettingStarted/InputDataView1.png
  docs/images/gettingStarted/InputDataView2.png
  docs/images/gettingStarted/NewDatasetDialog.png
  docs/images/gettingStarted/NewProjectDialog.png
  docs/images/gettingStarted/ProcessData1.png
  docs/images/gettingStarted/ProcessData2.png
  docs/images/gettingStarted/Results.png
  docs/images/gettingStarted/StartSearch.png
  docs/images/gettingStarted/runSearch/10StartSearchAndStartSearch.png
  docs/images/gettingStarted/runSearch/11StartSearchSearchProgress.png
  docs/images/gettingStarted/runSearch/12ResultsAndSolutionChart.png
  docs/images/gettingStarted/runSearch/13StopSearch.png
  docs/images/gettingStarted/runSearch/1ImportDataset.png
  docs/images/gettingStarted/runSearch/2ImportDatasetDialog.png
  docs/images/gettingStarted/runSearch/3NewProjectDialog.png
  docs/images/gettingStarted/runSearch/3bAddSearchDialog.png
  docs/images/gettingStarted/runSearch/4SelectDatasetInProject.png
  docs/images/gettingStarted/runSearch/5ProcessData.png
  docs/images/gettingStarted/runSearch/6SelectSearchAndDefineSearch.png
  docs/images/gettingStarted/runSearch/7DefineSearchSelectDataset.png
  docs/images/gettingStarted/runSearch/8DefineSearchChangeMutationAndCrossover.png
  docs/images/gettingStarted/runSearch/9SelectBuildingBlocks.png
  docs/index.md
Labels: documentation
